# Generated by Django 2.1.5 on 2019-01-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Okul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_school', models.CharField(max_length=50)),
                ('spening_year', models.IntegerField()),
                ('thinks_about_this', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'education',
            },
        ),
    ]
