# Generated by Django 2.1.5 on 2019-01-11 11:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('student_code', models.CharField(max_length=50)),
                ('detail_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='okul',
            name='thinks_about_this',
        ),
        migrations.AddField(
            model_name='okul',
            name='detail',
            field=models.CharField(default='', max_length=50),
        ),
    ]
