# Generated by Django 2.1.5 on 2019-01-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egitim', '0002_auto_20190111_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okul',
            name='spening_year',
        ),
    ]
