# Generated by Django 2.1.5 on 2019-01-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim', '0003_remove_okul_spening_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='okul',
            name='spening_year',
            field=models.IntegerField(default=666),
            preserve_default=False,
        ),
    ]
