# Generated by Django 2.1.5 on 2019-01-15 05:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitim', '0004_okul_spening_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SikimsonikModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
