# Generated by Django 2.1.5 on 2019-01-15 07:06

from django.db import migrations

def reverse_shell(apps, schema_editor):
    okullar = apps.get_model('egitim', 'Okul')
    studentdetail = apps.get_model('egitim', 'StudentDetail')

    for okul in okullar.objects.all():
        studentdetail(created_at = "6666-01-10",
        student_code="999",
        detail_data={
            'okul ismi': okul.name_of_school,
            'harcanan yıllar': okul.spening_year,
        }).save()

class Migration(migrations.Migration):

    dependencies = [
        ('egitim', '0005_sikimsonikmodel'),
    ]

    operations = [
        migrations.RunPython(reverse_shell),
    ]
