# Generated by Django 2.1.5 on 2019-01-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egitim', '0007_randomuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Okul',
        ),
        migrations.DeleteModel(
            name='SikimsonikModel',
        ),
        migrations.DeleteModel(
            name='StudentDetail',
        ),
    ]
